# Generated by Django 4.2.4 on 2023-09-04 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Federal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_required', models.BooleanField()),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords_app.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='congreso_search',
            field=models.ManyToManyField(to='keywords_app.states'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='estatal_search',
            field=models.ManyToManyField(related_name='estatal_search', to='keywords_app.states'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='federal_search',
            field=models.ManyToManyField(to='keywords_app.federal'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
