# Generated by Django 4.2.3 on 2023-08-23 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('aguascalientes', 'Aguascalientes'), ('baja_california_norte', 'Baja California Norte'), ('baja_california_sur', 'Baja California Sur'), ('campeche', 'Campeche'), ('chiapas', 'Chiapas'), ('chihuahua', 'Chihuahua'), ('ciudad_de_mexico', 'Ciudad de México'), ('coahuila', 'Coahuila'), ('colima', 'Colima'), ('durango', 'Durango'), ('guanajuato', 'Guanajuato'), ('guerrero', 'Guerrero'), ('hidalgo', 'Hidalgo'), ('jalisco', 'Jalisco'), ('mexico', 'México'), ('michoacan', 'Michoacán'), ('morelos', 'Morelos'), ('nayarit', 'Nayarit'), ('nuevo_leon', 'Nuevo León'), ('oaxaca', 'Oaxaca'), ('puebla', 'Puebla'), ('queretaro', 'Querétaro'), ('quintana_roo', 'Quintana Roo'), ('san_luis_potosi', 'San Luis Potosí'), ('sinaloa', 'Sinaloa'), ('sonora', 'Sonora'), ('tabasco', 'Tabasco'), ('tamaulipas', 'Tamaulipas'), ('tlaxcala', 'Tlaxcala'), ('veracruz', 'Veracruz'), ('yucatan', 'Yucatán'), ('zacatecas', 'Zacatecas')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_keyword', models.CharField(max_length=50)),
                ('second_keyword', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('states_to_search', models.ManyToManyField(to='keywords_app.states')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
