# Generated by Django 4.2.4 on 2023-09-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='congreso_search',
            field=models.ManyToManyField(blank=True, to='keywords_app.states'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='estatal_search',
            field=models.ManyToManyField(blank=True, related_name='estatal_search', to='keywords_app.states'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='federal_search',
            field=models.ManyToManyField(blank=True, to='keywords_app.federal'),
        ),
    ]
