# Generated by Django 4.2.3 on 2023-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='second_keyword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
