# Generated by Django 4.2.3 on 2023-08-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0002_alter_keyword_second_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='state',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
