# Generated by Django 4.2.4 on 2023-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0002_alter_keyword_congreso_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='title',
            field=models.CharField(default='titulo', max_length=60),
            preserve_default=False,
        ),
    ]
