# Generated by Django 4.2.4 on 2023-08-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0003_alter_states_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='states_to_search',
            new_name='congreso_search',
        ),
    ]
