# Generated by Django 4.2.4 on 2023-09-19 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0003_keyword_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 9, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 9, 19)),
            preserve_default=False,
        ),
    ]
