# Generated by Django 4.2.4 on 2023-09-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0004_keyword_end_date_keyword_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
