# Generated by Django 4.2.4 on 2023-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0005_keyword_estatal_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('federal', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='federal_search',
            field=models.ManyToManyField(to='keywords_app.federal'),
        ),
    ]
