# Generated by Django 4.2.5 on 2023-09-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0005_alter_keyword_end_date_alter_keyword_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
