# Generated by Django 4.2.6 on 2023-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0006_alter_keyword_end_date_alter_keyword_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
