# Generated by Django 4.2.6 on 2024-01-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords_app', '0007_alter_keyword_end_date_alter_keyword_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='is_mail_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
