# Generated by Django 4.2.2 on 2023-07-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBaseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=127, null=True)),
                ('category', models.CharField(choices=[('ADMINISTRADOR', 'administrador'), ('USUARIO', 'usuario'), ('CLIENTE', 'cliente')], max_length=13)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_birth', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
