# Generated by Django 4.2.2 on 2023-07-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBaseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('address', models.TextField(max_length=255)),
                ('company', models.CharField(max_length=127)),
                ('user_type', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('USUARIO', 'Usuario'), ('CLIENTE', 'Cliente')], max_length=13)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_birth', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tipos_usuarios.userbaseaccount',),
        ),
    ]
