# Generated by Django 4.2.2 on 2023-07-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tipos_usuarios.userbaseaccount',),
        ),
    ]
