# Generated by Django 4.2.4 on 2023-09-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbaseaccount',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        )
    ]
