# Generated by Django 4.2.5 on 2023-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_usuarios', '0005_userbaseaccount_groups_userbaseaccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbaseaccount',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
