# Generated by Django 4.2.6 on 2024-01-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_usuarios', '0007_userbaseaccount_is_active_userbaseaccount_last_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbaseaccount',
            name='mail_notifications_active',
        ),
    ]
