# Generated by Django 4.2.6 on 2024-03-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_usuarios', '0009_rename_last_mail_userbaseaccount_next_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbaseaccount',
            name='terms_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
